<?php
// $Id: activitystream_github.module,v 1.1 2010/01/18 05:01:37 cweagans Exp $

/**
 * @author : Cameron Eagans (me@cweagans.net)
 * @file
 * The module for importing Github activity.
 */

/*
 * The API passes in a $user object that contains four properties:
 * uid, userid, password, feed. These properties contain the account
 * information entered into the user's settings page, along with the 
 * uid of their Drupal account.
 */
function activitystream_github_streamapi($user) {
  // This user doesn't have a Github ID entered
  if (!$user->userid) {
    return;
  }
  
  // Use the activitystream_feed module to pull in the user's github activity.
  $user->feed = 'http://github.com/' . $user->userid . '.atom';
  $activity = activitystream_feed_streamapi($user);
  return $activity;
}

/*
 * Implement a user settings form hook. Modules should build a form
 * using an array that mirrors the Drupal form API. activitystream.module
 * will add the form elements to a tab called Activity Streams on the
 * user's Profile Edit page. Fields should be named
 * yourmodulename_fieldname. For instance, to store the user ID for 
 * Flickr, the field name is activitystream_flickr_userid
 *
 * To avoid collisions with other activitystream module's forms
 * use your module's name as the form array's key.
 *
 * @param $edit
 *   The values of the form fields, used for setting defaults
 * 
 */
function activitystream_github_activitystream_settings(&$edit) {
	//print_r($edit);
  $form['activitystream_github'] = array(
     '#type' => 'fieldset',
    '#title' => t('Github settings')
  );
  $form['activitystream_github']['activitystream_github_userid'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#default_value' => empty($edit['activitystream_github_userid']) ? '' : $edit['activitystream_github_userid'],
    '#description' => t('The username for your Github account.')
  );
  return $form;  
}

function theme_activitystream_github_icon() {
  return theme_image(drupal_get_path('module', 'activitystream_github') .'/github_logo.png', 'Github');
}

function theme_activitystream_github_item($activity) {
  $node = node_load($activity->nid);
  $date = theme('activitystream_date', $node->created);
  $user = activitystream_user_load($node->uid);
  $name = theme('activitystream_username', $user);
  return '<span class="activitystream-item">'. theme('activitystream_github_icon') ." <span>$name ". l(preg_replace('/^(\w*)/', '', $node->title), $activity->link) ." <span class=\"activitystream-created\">$date</span></span>". l('#', 'node/'. $node->nid, array('class' => 'permalink')) .'</span>';
}

function activitystream_github_theme() {
  return array(
    'activitystream_github_icon' => array(
      'arguments' => array(),
    ),
    'activitystream_github_item' => array(
      'arguments' => array('activity' => NULL),
    ),
  );
}

