<?php
// $Id$
/**
 * @author : Heshan Wanigasooriy (heshan@heidisoft.com)
 * @file
 * The module for importing Facebook activity.
 */

/*
 * The API passes in a $user object that contains four properties:
 * uid, userid, password, feed. These properties contain the account
 * information entered into the user's settings page, along with the 
 * uid of their Drupal account.
 */
function activitystream_facebook_streamapi($user) {

  // This user doesn't have a Facebook ID entered
  if (!$user->feed) {
    return;
  }

  // Use the activitystream_feed module to pull in the user's
  // history.
  $user->feed = $user->feed;//
  //'http://www.new.facebook.com/feeds/status.php?id='.$user->userid .'&viewer='.$user->userid.'&key='.$user->extra.'&format=rss20';
  //$user->feed ='http://www.new.facebook.com/feeds/status.php?id=652116749&viewer=652116749&key=5e35fdee0b&format=rss20';
  $items = activitystream_feed_streamapi($user);
  return $items;
}


/*
 * Implement a user settings form hook. Modules should build a form
 * using an array that mirrors the Drupal form API. activitystream.module
 * will add the form elements to a tab called Activity Streams on the
 * user's Profile Edit page. Fields should be named
 * yourmodulename_fieldname. For instance, to store the user ID for 
 * Flickr, the field name is activitystream_flickr_userid
 *
 * To avoid collisions with other activitystream module's forms
 * use your module's name as the form array's key.
 *
 * @param $edit
 *   The values of the form fields, used for setting defaults
 * 
 */
function activitystream_facebook_activitystream_settings(&$edit) {
  $form['activitystream_facebook'] = array(
      '#type' => 'fieldset',
      '#title' => t('Facebook Settings'));
  $form['activitystream_facebook']['activitystream_facebook_feed'] = array(
    '#type' => 'textfield',
    '#title' => t('Facebook Status RSS feed URL'),
    '#default_value' => empty($edit['activitystream_facebook_feed']) ? '' : $edit['activitystream_facebook_feed'],
    '#description' => t('<a href="http://heidisoft.com/blogs/subscribe-new-facebook-feeds" target="_blank">Click here</a> for more information'));
   return $form;  
}

function theme_activitystream_facebook_icon() {
  return theme_image(drupal_get_path('module', 'activitystream_facebook') .'/facebook.png', 'Facebook');
}

function theme_activitystream_facebook_item($activity) {
  $node = node_load($activity->nid);
  $date = theme('activitystream_date', $node->created);
  $user = activitystream_user_load($node->uid);
  $name = theme('activitystream_username', $user);
  return '<span class="activitystream-item">'. theme('activitystream_facebook_icon')   . " <span>$name " . l($node->title, $activity->link) ." <span class=\"activitystream-created\">$date</span></span>". l('#', 'node/'. $node->nid, array('class' => 'permalink')) .'</span>';
}

function activitystream_facebook_theme() {
  return array(
    'activitystream_facebook_icon' => array(
      'arguments' => array(),
    ),
    'activitystream_facebook_item' => array(
      'arguments' => array('activity' => NULL),
    ),
  );
}